### PR TITLE
add ejs

### PR DESCRIPTION
**Pull request by zophiale**

### CODE REVIEW

**Comment by dispherical** [comment]
Can you please be a bit more descriptive?

**Comment by khalby786** [comment]
@Jonyk56 this list accepts only Glitch-based projects, not frameworks and templating engines used! I will have to remove @RiversideRocks's Discord.js from the list.

**Comment by dispherical** [comment]
Should I remove halfmoon then?

**Comment by trentwiles** [comment]
Uh, Halfmoon is not Glitch based?

**Comment by trentwiles** [comment]
Really confused

**Comment by khalby786** [comment]
@aboutDavid @RiversideRocks yes, might need to remove Halfmoon, this is a curated list of Glitch projects not frameworks and libraries used.

**Comment by trentwiles** [comment]
I thought the description said it was frameworks that could be used on glitch?

**Comment by dispherical** [comment]
> I thought the description said it was frameworks that could be used on glitch?

Yeah, that's also what I thought

**Comment by khalby786** [comment]
@Jonyk56 @RiversideRocks @aboutDavid I'm currently in the process of setting up this Awesome list.

And Awesome list has a lot of guidelines and rules to follow, and we also need to subdivide our collection into categories based on which we can suitably categorize projects.

Until then, I advise not to open PRs or merge them because there's a CLI tool that allows you to quickly create an Awesome list without much hassle, which I'm working on locally.

I'm also thinking of inviting a Glitch staff member (like Jenn) because they know more which all projects are awesome.

I'm thinking of creating a huge list of awesome projects initially, and then gradually with the help of everyone we'll categorize them suitably.

**Comment by oldalt** [comment]
I don't expect that to happen though. The staff of Glitch don't join random github repos, though they can make a pull request

**Comment by khalby786** [comment]
Let's see what happens... 😏😌

**Pull request closed without merging**
